#! /usr/bin/env bash

export PYTHONPATH=$PYTHONPATH:../lib

command=$1

exec_for() {
    echo "$1..."
    "./$command" < "./samples/FSSPSC_$1.txt" > "./samples/FSSPSC_$1.sol" 2> "./samples/FSSPSC_$1.data"
    echo "$1 done!"
}

for i in $(seq 1 1 120); do
    ( exec_for $i )
done
